[package]
name = "neuralnet_mnist"
version = "0.1.0"
authors = ["Colin Pitrat <colin.pitrat@gmail.com>"]
edition = "2018"

[dev-dependencies]
assert_matches = "1.3.0"

[dependencies]
byteorder = "1.3.2"
itertools = "0.8.0"
tempfile = "3.1.0"
