[package]
name = "lissajous"
version = "0.1.0"
authors = ["Colin Pitrat <colin.pitrat@gmail.com>"]

[dependencies]

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["ttf", "image", "gfx"]
