[package]
name = "althreat"
version = "0.1.0"
authors = ["Colin Pitrat <colin.pitrat@gmail.com>"]

[dependencies]
rand = "0.5.5"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["ttf", "image", "gfx"]
