[package]
name = "day24"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
argh = "0.1.12"
fastrand = "2.3.0"
gomez = "0.5.0"
nalgebra = "0.33.2"
peroxide = { version = "0.39.0", features = ["O3"] }
rand = "0.8.5"
